title: cli-log
description: cli-log is a pypi package used create log messages in a command line interface.
github:
  pypi: https://pypi.org/project/cli-log/
show_downloads: true
google_analytics:
remote_theme: pages-themes/cayman@v0.2.0
google_analytics_anonymize: false
darkmode: true
hide_first_title: true # Useful if README.md is used on both github and pages
logo_url: ./assets/images/deltabotics_transp.png
colors:
    gradient_left: "#155799"
    gradient_right: "#159957"
    header: "#fff"
    android_theme: "#000" # this default to gradient_color
    link: "#1e6bb8" # this default to gradient_color
    section_title: "#155799" # this default to gradient_color
buttons:
      zip_url: http://example.com/
      zip_title: Title
      zip_hide: true
      tar_url: http://example.com/
      tar_title: Title
      tar_hide: true
      github_hide: false # hides "View on Github"

# Tried using different theme, didnt work, so if someones wondering why this is so large
